# Numpy vs Lists 

In [3]:
#Let's define a list in python.
heights = [74, 75, 72, 72, 71]

In [4]:
# Print the heights.
heights

[74, 75, 72, 72, 71]

In [5]:
# Try to multiple heights with a scalar.
heights * 2.54

TypeError: can't multiply sequence by non-int of type 'float'

In [7]:
import numpy as np

In [8]:
# Deine a NumPy array
np_heights = np.array([74, 75, 72, 72, 71])

In [9]:
np_heights

array([74, 75, 72, 72, 71])

In [10]:
# Print the type of a NumPy array.
type(np_heights)

numpy.ndarray

In [11]:
# Multiple height (NumPy array) with a scalar.
np_heights * 2.54

array([187.96, 190.5 , 182.88, 182.88, 180.34])


#### NumPy comes with its own set of methods and operations

In [14]:
# Let's define two lists and perform '+' operation on that.
list_1 = [1,2,3]
list_2 = [4,5,6]
list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [13]:
# Let's define two NumPy array and perform '+' operation on that.
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])
np1 + np2

array([5, 7, 9])

#### Working with N-D Arrays

In [45]:
np_heights

array([74, 75, 72, 72, 71])

In [46]:
type(np_heights)

numpy.ndarray